# Generated by Django 2.2.6 on 2021-06-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_newpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
